apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: greenops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: greenops-config
                  key: postgres-user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: greenops-config
                  key: postgres-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: greenops-secrets
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc