apiVersion: v1
kind: Secret
metadata:
  name: greenops-secrets
  namespace: greenops
type: Opaque
stringData:
  postgres-password: SuperSecretPassword2026
  jwt-secret: MonSecretUltraSecurisePourLeTokenJWT2026